import 'package:get/get.dart';

class ArabicEnglishLocal implements Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    "en": {
      'app_name': "Smart Path",
      // For Auth
      'title_pin': 'Enter PIN',
      'desc_pin': 'Please enter your 4-digit PIN to\ncontinue.',
      'error_pin': 'PIN code is wrong',
      'option_pin_title': 'or',
      'option_pin_desc': 'use biometric',
      'bio_messagge': 'Please complete authentication',
      // For introduction_pages
      'introduction_title': 'Welcome to Smart Path!',
      'introduction_content_0': 'You are in the right place',
      'introduction_content_1': 'Be with us on the amazing path',
      'introduction_content_2': 'anything very easy to use',
      // For login
      'sign_in': 'Sign In',
      'sign_in_desc': 'Hi there! Nice to see you again',
      'email': 'E-mail',
      'email-valid_empty': 'Email cannot be empty',
      'email-valid_weak': 'Email is invalid',
      'password': 'Password',
      'password_valid_empty': 'Password cannot be empty',
      'password_valid_weak': 'Password is too weak',
      'forgot_password': 'Forgot Password',
      'error': 'Error',
      'error_message':
          'Please check your internet connection and try again later',
      // For request password
      'request_email_title': 'E-mail Required',
      'request_email_desc': 'Please enter your email below',
      'send': 'Send',
      // For enter verification vode
      'verification_code': 'Verification Code',
      'verification_code_desc': 'Please type the verification code sent\nto ',
      'limit_empty': 'you have reached your attempts limit, request a new otp',
      'You have': 'You have',
      'attempts': 'attempts',
      // For otp
      'error_in_code': 'Please check the verification code',
      // For reset password
      'reset_tite': 'Reset Password',
      'reset_desc': 'Please enter your password',
      'password_reset': 'Password',
      'password_confirm_reset': 'Confirm Password',
      'password_valid': 'Passwords are different',
      // NavBar
      'home': 'Home',
      'portfolio': 'Portfolio',
      'input': 'Input',
      'profile': 'Profile',
      // Home page student
      'app_bar_home_stu_title': 'Student Portfolio',
      'hi': 'Hi',
      'search_bar_home_hint': 'Looking for...',
      'welcome-content': 'Easily create and share\nyour own awesome portfolio',
      'grid_item_name_0': 'Class',
      'grid_item_name_1': 'Courses',
      'grid_item_name_2': 'Homeworks',
      'grid_item_name_3': 'Weekly\nSchedule',
      'grid_item_name_4': 'Quiz',
      'grid_item_name_5': 'Subscribe',
      'grid_item_name_6': 'Grades',
      'grid_item_name_7': 'Events',
      'grid_item_name_8': 'Exam\nSchedule',
      'grid_item_name_9': 'Project',
      'grid_item_name_10': 'Idea',
      'grid_item_name_11': 'Subjects',
      // For Calendar
      'schedule_title_page': 'Weekly Schedule',
      'Sun': 'Sun',
      'Mon': 'Mon',
      'Tues': 'Tues',
      'Wed': 'Wed',
      'Thurs': 'Thurs',
      // For filter page
      'filter_page_title': 'Filter',
      'filter_desc': 'We need some information to continue',
      'title_field_1': 'Select the year with the semester',
      'title_field_2': 'Select the type',
      'First': 'First',
      'Second': 'Second',
      'type_0': 'Final',
      // 'type_1': 'Mid-Term',
      'type_1': 'Quiz', // TODO
      'button_text': 'Next',
      'field_validation_text': 'This field cannot be empty',
      'No results at the moment': 'No results at the moment',
      // For grades
      'average': 'Average',
      // Profile
      'change_password': 'Change Password',
      'about': 'About',
      'help': 'Help',
      'contact': 'Contact',
      'sign_out': 'Sign Out',
      'title_page': 'Your Profile',
      'profile_info_title': "Profile Info",
      'class': 'Class',
      'status': 'Status',
      'school': 'School',
      'rate': 'Rate',
      'email-info': 'E-mail',
      'phone': 'Phone',
      'address': 'Address',
      // For settings
      'Settings': 'Settings',
      'lang_title': 'Choose a language',
      'Arabic': 'Arabic',
      'English': 'English',
      'Lock App': 'Lock App',
      'pin_desc': 'Please enter your PIN below',
      'confirm_title': 'Confirm PIN Code',
      'confirm_desc': 'Please enter your PIN again',
      'confirm_error': 'Please enter the same code',
      'lock_title': 'Enable App lock',
      'fingerprint_title': 'Fingerprint',
      'change_title': 'Change PIN',
      'verify_title': 'Verify Identity',
      'vPin_title': 'PIN Code',
      'vPin_error': 'PIN is wrong',
      // For About
      'page_title_about': 'About',
      'aboutApp_title': 'About The App',
      'aboutApp_desc':
          'The Smart Pathh is a smart platform designed to enhance communication between the school, students, and parents. It offers easy and secure access to attendance records, academic performance, class schedules, assignments, and important announcements — all in one place',
      'aboutSc_title': 'About the School',
      'aboutSc_desc':
          'Al-Riyada Model School is a leading educational institution committed to academic excellence and providing a stimulating learning environment. Our goal is to combine quality education, strong values, and modern technology to serve our students and community',
      'version': 'App Version',
      'rights': 'Copyright',
      'rights_desc': 'All rights reserved to Al-Riyada Model School',
      // For Contact
      'page_title': 'Contact',
      'page_desc':
          'If you have any questions or need assistance, feel free to contact us through any of the methods listed below. We are here to help!',
      'address_title': 'Address',
      'address_content': 'Education City, Al-Riyada Street',
      'phone_title': 'Phone',
      'email_title': 'Email',
      'website_title': 'Official website',
      'facebook_title': 'Facebook',
      'working_title': 'Working Hours',
      'working_day': 'Sunday - Thursday',
      'holiday_day': 'Friday - Saturday',
      'holiday_desc': 'Closed',
      'button_call': 'Call Us',
      'button_send': 'Send Email',
      'button_visitW': 'Visit Website',
      'button_visitF': 'Visit Facebook',
      //librarian
      'borrow_manage': 'Borrow management',
      'lib_grid_1': 'Books',
      'lib_grid_2': 'available books',
      'lib_grid_3': 'Borrow request',
      'lib_grid_4': 'Accepted request',
      'lib_grid_5': 'Rejected request',
      'books': 'Books',
      // librarian add a book
      'add_book': 'Add Book',
      'title': 'Title',
      'author': 'Author',
      'category': 'Category',
      'publisher': 'Publisher',
      'serial_number': 'Serial Number',
      'shelf_location': 'Shelf Location',
      'description': 'Description',
      'add_book_success': 'Book added successfully!',
      'required_field': 'This field is required',
      'submit': 'Submit',
      'edit': 'Edit',
      'delete': 'Delete',
      'delete_confirm': 'Are you sure you want to delete this book?',
      'ok': 'Ok',
      'yes': 'Yes',
      'no': 'No',
      'cancel': 'Cancel',
    },
    "ar": {
      'app_name': "المسار الذكي",
      // For Auth
      'title_pin': 'أدخل رقم التعريف\nالشخصي',
      'desc_pin': 'الرجاء إدخال رقم التعريف الشخصي\nالمكون من 4 أرقام للمتابعة',
      'error_pin': 'رمز PIN خاطئ',
      'option_pin_title': 'أو',
      'option_pin_desc': 'استخدم بصمة الإصبع',
      'bio_messagge': 'الرجاء إكمال المصادقة',
      // For introduction_pages
      'introduction_title': 'مرحباً بكم في المسار الذكي!',
      'introduction_content_0': 'أنت في المكان المناسب',
      'introduction_content_1': 'كن معنا في الطريق المذهل',
      'introduction_content_2': 'هنا أي شيء سهل الاستخدام للغاية',
      // For login
      'sign_in': 'تسجيل الدخول',
      'sign_in_desc': 'مرحباً! سررت برؤيتك مجدداً',
      'email': 'البريد إلكتروني',
      'email-valid_empty': 'لا يمكن أن يكون البريد الإلكتروني فارغًا',
      'email-valid_weak': 'البريد الإلكتروني غير صالح',
      'password': 'كلمة السر',
      'password_valid_empty': 'لا يمكن أن تكون كلمة المرور فارغة',
      'password_valid_weak': 'كلمة المرور ضعيفة جدًا',
      'forgot_password': 'هل نسيت كلمة السر',
      'error': 'خطأ',
      'error_message':
          'يرجى التحقق من اتصالك بالإنترنت والمحاولة مرة أخرى لاحقًا',
      // For request password
      'request_email_title': 'البريد الإلكتروني مطلوب',
      'request_email_desc': 'الرجاء إدخال بريدك الإلكتروني أدناه',
      'send': 'إرسال',
      // For enter verification vode
      'verification_code': 'رمز التحقق',
      'verification_code_desc': 'الرجاء كتابة رمز التحقق المرسل إلى ',
      'limit_empty': 'لقد وصلت إلى الحد الأقصى للمحاولات، اطلب رمز تحقق جديد',
      'You have': 'لديك',
      'attempts': 'محاولات',
      // For otp
      'error_in_code': 'الرجاء التأكد من رمز التحقق',
      // For reset password
      'reset_tite': 'إعادة تعيين كلمة المرور',
      'reset_desc': 'الرجاء إدخال كلمة المرور الخاصة بك',
      'password_reset': 'كلمة المرور',
      'password_confirm_reset': 'تأكيد كلمة المرور',
      'password_valid': 'كلمات المرور مختلفة',
      // NavBar
      'home': 'الرئيسية',
      'portfolio': 'الإنجازات',
      'input': 'إدخال',
      'profile': 'الملف الشخصي',
      //Home page student
      'app_bar_home_stu_title': 'ملف الطالب',
      'hi': 'مرحباً',
      'search_bar_home_hint': 'ابحث عن',
      'welcome-content': 'قم بإنشاء ومشاركة\nمحفظتك الرائعة بسهولة',
      'grid_item_name_0': 'الفصل الدراسي',
      'grid_item_name_1': 'الدورات',
      'grid_item_name_2': 'الوظائف',
      'grid_item_name_3': 'برنامج\nالإسبوع',
      'grid_item_name_4': 'إختبار',
      'grid_item_name_5': 'الإشتراكات',
      'grid_item_name_6': 'الدرجات',
      'grid_item_name_7': 'الأحداث',
      'grid_item_name_8': 'برنامج\nالإمتحان',
      'grid_item_name_9': 'المشاريع',
      'grid_item_name_10': 'الأفكار',
      'grid_item_name_11': 'المواد الدراسية',
      // For Calendar
      'schedule_title_page': 'برنامج الإسبوع',
      'Sun': 'الأحد',
      'Mon': 'الإثنين',
      'Tues': 'الثلاثاء',
      'Wed': 'الأربعاء',
      'Thurs': 'الخميس',
      // For filter page
      'filter_page_title': 'فلتر',
      'filter_desc': 'نحن بحاجة إلى بعض المعلومات للاستمرار',
      'title_field_1': 'حدد السنة مع الفصل الدراسي',
      'title_field_2': 'حدد النوع',
      'First': 'الفصل الأول',
      'Second': 'الفصل الثاني',
      'type_0': 'الإمتحان النهائي',
      // 'type_1': 'الإمتحان النصفي',
      'type_1': 'إختبار', // TODO
      'button_text': 'التالي',
      'field_validation_text': 'لا يمكن أن يكون هذا الحقل فارغًا',
      'No results at the moment': 'لا توجد نتائج في الوقت الحالي',
      // For grades
      'average': 'المعدل',
      // Profile
      'change_password': 'تغيير كلمة المرور',
      'about': 'عن',
      'help': 'يساعد',
      'contact': 'اتصل بنا',
      'sign_out': 'تسجيل الخروج',
      'title_page': 'ملفك الشخصي',
      'profile_info_title': "معلومات الملف الشخصي",
      'class': 'الصف',
      'status': 'الحالة',
      'school': 'المدرسة',
      'rate': 'المعدل',
      'email-info': 'البريد الإلكتروني',
      'phone': 'الهاتف',
      'address': 'العنوان',
      // For settings
      'Settings': 'الإعدادات',
      'lang_title': 'اختر لغة',
      'Arabic': 'اللغة العربية',
      'English': 'اللغة الإنجليزية',
      'Lock App': 'قفل التطبيق',
      'pin_desc': 'الرجاء إدخال رقم التعريف الشخصي الخاص بك أدناه',
      'confirm_title': 'تأكيد رمز PIN',
      'confirm_desc': 'الرجاء إدخال رقم التعريف الشخصي\nالخاص بك مرة أخرى',
      'confirm_error': 'الرجاء إدخال نفس الرمز',
      'lock_title': 'تمكين قفل التطبيق',
      'fingerprint_title': 'بصمة',
      'change_title': 'تغيير رقم التعريف الشخصي',
      'verify_title': 'التحقق من الهوية',
      'vPin_title': 'رمز التعريف الشخصي',
      'vPin_error': 'رقم التعريف الشخصي غير صحيح',
      // For About
      'page_title_about': 'عن',
      'aboutApp_title': 'عن التطبيق',
      'aboutApp_desc':
          'المسار الذكي منصة ذكية مصممة لتعزيز التواصل بين المدرسة والطلاب وأولياء الأمور. توفر وصولاً سهلاً وآمنًا إلى سجلات الحضور، والأداء الأكاديمي، وجداول الحصص، والواجبات، والإعلانات المهمة - كل ذلك في مكان واحد',
      'aboutSc_title': 'عن المدرسة',
      'aboutSc_desc':
          'مدرسة الريادة النموذجية مؤسسة تعليمية رائدة ملتزمة بالتميز الأكاديمي وتوفير بيئة تعليمية محفزة. هدفنا هو الجمع بين جودة التعليم والقيم الراسخة والتكنولوجيا الحديثة لخدمة طلابنا ومجتمعنا',
      'version': 'إصدار التطبيق',
      'rights': 'حقوق الطبع والنشر',
      'rights_desc': 'جميع الحقوق محفوظة لمدرسة الريادة النموذجية',
      // For Contact
      'page_title': 'اتصل بنا',
      'page_desc':
          'إذا كانت لديك أي أسئلة أو كنت بحاجة إلى مساعدة، فلا تتردد في التواصل معنا عبر أي من الطرق المذكورة أدناه. نحن هنا لمساعدتك!',
      'address_title': 'العنوان',
      'address_content': 'المدينة التعليمية, شارع الريادة',
      'phone_title': 'الهاتف المحمول',
      'email_title': 'البريد الإلكتروني',
      'website_title': 'الموقع الرسمي',
      'facebook_title': 'فيسبوك',
      'working_title': 'ساعات العمل',
      'working_day': 'الأحد - الخميس',
      'holiday_day': 'الجمعة - السبت',
      'holiday_desc': 'مغلق',
      'button_call': 'اتصل بنا',
      'button_send': 'أرسل بريداً إلكترونياً',
      'button_visitW': 'زر الموقع',
      'button_visitF': 'زر فيسبوك',

      // For Events
      'one_comment': 'تعليق واحد',
      'two_comment': 'تعليقان',
      'many_comment': 'تعليقات',
      'comment_button': 'تعليق',
      'one_share': 'مشاركة واحدة',
      'two_share': 'مشاركتان',
      'many_share': 'مشاركات',
      'share_button': 'مشاركة',
      'Like': 'أعجبني',
      'Love': 'أحببته',
      'Wow': 'واو',
      'Angry': 'أغضبني',
      'Haha': 'هاها',
      'Sad': 'أحزنني',
      // For ReactionInfo
      'all_button': 'الجميع',
      // For Comment Page
      'comment_title_page': 'التعليقات',
      'edit_button': 'تعديل التعليق',
      'report_button': 'الإبلاغ عن التعليق',
      'delete_button': 'حذف التعليق',
      'comment_error': 'يرجى التحقق من اتصالك بالإنترنت والمحاولة لاحقاً',
      'like_button': 'أعجبني',
      'reply_button': 'رد',
      'read_button': 'اقرأ المزيد',
      'one_replies': 'رد واحد',
      'two_replies': 'ردان',
      'many_replies': 'ردود',
      'field_title': 'أكتب تعليق...',

      //librarian
      'borrow_manage': 'ادارة الاستعارة',
      'lib_grid_1': 'الكتب',
      'lib_grid_2': 'الكتب المتاحة',
      'lib_grid_3': 'طلب استعارة',
      'lib_grid_4': 'الطلبات المقبولة',
      'lib_grid_5': 'الطلبات المرفوضة',
      'books': 'الكتب',
      // librarian add a book
      'add_book': 'إضافة كتاب',
      'title': 'العنوان',
      'author': 'المؤلف',
      'category': 'الفئة',
      'publisher': 'الناشر',
      'serial_number': 'الرقم التسلسلي',
      'shelf_location': 'مكان الرف',
      'description': 'الوصف',
      'add_book_success': 'تمت إضافة الكتاب بنجاح!',
      'required_field': 'هذا الحقل مطلوب',
      'submit': 'إرسال',
      'edit': 'تعديل',
      'delete': 'حذف',
      'delete_confirm': 'هل أنت متأكد أنك تريد حذف هذا الكتاب؟',
      'ok': 'حسنا',
      'yes': 'نعم',
      'no': 'لا',
    },
  };
}
