import 'package:get/get.dart';

class ArabicEnglishLocal implements Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    "en": {
      'app_name': "Smart Path",
      // For introduction_pages
      'introduction_title': 'Welcome to Smart Path!',
      'introduction_content_0': 'You are in the right place',
      'introduction_content_1': 'Be with us on the amazing path',
      'introduction_content_2': 'anything very easy to use',
      // For login
      'sign_in': 'Sign In',
      'sign_in_desc': 'Hi there! Nice to see you again',
      'email': 'E-mail',
      'email-valid_empty': 'Email cannot be empty',
      'email-valid_weak': 'Email is invalid',
      'password': 'Password',
      'password_valid_empty': 'Password cannot be empty',
      'password_valid_weak': 'Password is too weak',
      'forgot_password': 'Forgot Password',
      'error': 'Error',
      'error_message':
          'Please check your internet connection and try again later',
      // For request password
      'request_email_title': 'E-mail Required',
      'request_email_desc': 'Please enter your email below',
      'send': 'Send',
      // For enter verification vode
      'verification_code': 'Verification Code',
      'verification_code_desc': 'Please type the verification code sent\nto ',
      'limit_empty': 'you have reached your attempts limit, request a new otp',
      'You have': 'You have',
      'attempts': 'attempts',
      // For otp
      'error_in_code': 'Please check the verification code',
      // For reset password
      'reset_tite': 'Reset Password',
      'reset_desc': 'Please enter your password',
      'password_reset': 'Password',
      'password_confirm_reset': 'Confirm Password',
      'password_valid': 'Passwords are different',
      // NavBar
      'home': 'Home',
      'portfolio': 'Portfolio',
      'input': 'Input',
      'profile': 'Profile',
      // Home page student
      'app_bar_home_stu_title': 'Student Portfolio',
      'hi': 'Hi',
      'search_bar_home_hint': 'Looking for...',
      'welcome-content': 'Easily create and share\nyour own awesome portfolio',
      'grid_item_name_0': 'Class',
      'grid_item_name_1': 'Courses',
      'grid_item_name_2': 'Homeworks',
      'grid_item_name_3': 'Weekly\nSchedule',
      'grid_item_name_4': 'Quiz',
      'grid_item_name_5': 'Subscribe',
      'grid_item_name_6': 'Grades',
      'grid_item_name_7': 'Events',
      'grid_item_name_8': 'Exam\nSchedule',
      'grid_item_name_9': 'Project',
      'grid_item_name_10': 'Idea',
      'grid_item_name_11': 'Subjects',
      // For Calendar
      'schedule_title_page': 'Weekly Schedule',
      'Sun': 'Sun',
      'Mon': 'Mon',
      'Tues': 'Tues',
      'Wed': 'Wed',
      'Thurs': 'Thurs',
      // For filter page
      'filter_page_title': 'Filter',
      'filter_desc': 'We need some information to continue',
      'title_field_1': 'Select a year',
      'title_field_2': 'Select the type',
      'type_0': 'Final',
      'type_1': 'Mid',
      'type_2': 'Quiz',
      'button_text': 'Next',
      'field_validation_text': 'This field cannot be empty',
      // For grades
      'average': 'Average',
      // Profile
      'change_password': 'Change Password',
      'about': 'About',
      'help': 'Help',
      'contact': 'Contact',
      'sign_out': 'Sign Out',
      'title_page': 'Your Profile',
      'profile_info_title': "Profile Info",
      'class': 'Class',
      'status': 'Status',
      'school': 'School',
      'rate': 'Rate',
      'email-info': 'E-mail',
      'phone': 'Phone',
      'address': 'Address',
    },
    "ar": {
      'app_name': "المسار الذكي",
      // For introduction_pages
      'introduction_title': 'مرحباً بكم في المسار الذكي!',
      'introduction_content_0': 'أنت في المكان المناسب',
      'introduction_content_1': 'كن معنا في الطريق المذهل',
      'introduction_content_2': 'هنا أي شيء سهل الاستخدام للغاية',
      // For login
      'sign_in': 'تسجيل الدخول',
      'sign_in_desc': 'مرحباً! سررت برؤيتك مجدداً',
      'email': 'البريد إلكتروني',
      'email-valid_empty': 'لا يمكن أن يكون البريد الإلكتروني فارغًا',
      'email-valid_weak': 'البريد الإلكتروني غير صالح',
      'password': 'كلمة السر',
      'password_valid_empty': 'لا يمكن أن تكون كلمة المرور فارغة',
      'password_valid_weak': 'كلمة المرور ضعيفة جدًا',
      'forgot_password': 'هل نسيت كلمة السر',
      'error': 'خطأ',
      'error_message':
          'يرجى التحقق من اتصالك بالإنترنت والمحاولة مرة أخرى لاحقًا',
      // For request password
      'request_email_title': 'البريد الإلكتروني مطلوب',
      'request_email_desc': 'الرجاء إدخال بريدك الإلكتروني أدناه',
      'send': 'إرسال',
      // For enter verification vode
      'verification_code': 'رمز التحقق',
      'verification_code_desc': 'الرجاء كتابة رمز التحقق المرسل إلى ',
      'limit_empty': 'لقد وصلت إلى الحد الأقصى للمحاولات، اطلب رمز تحقق جديد',
      'You have': 'لديك',
      'attempts': 'محاولات',
      // For otp
      'error_in_code': 'الرجاء التأكد من رمز التحقق',
      // For reset password
      'reset_tite': 'إعادة تعيين كلمة المرور',
      'reset_desc': 'الرجاء إدخال كلمة المرور الخاصة بك',
      'password_reset': 'كلمة المرور',
      'password_confirm_reset': 'تأكيد كلمة المرور',
      'password_valid': 'كلمات المرور مختلفة',
      // NavBar
      'home': 'الرئيسية',
      'portfolio': 'الإنجازات',
      'input': 'إدخال',
      'profile': 'الملف الشخصي',
      //Home page student
      'app_bar_home_stu_title': 'ملف الطالب',
      'hi': 'مرحباً',
      'search_bar_home_hint': 'ابحث عن',
      'welcome-content': 'قم بإنشاء ومشاركة\nمحفظتك الرائعة بسهولة',
      'grid_item_name_0': 'الفصل الدراسي',
      'grid_item_name_1': 'الدورات',
      'grid_item_name_2': 'الوظائف',
      'grid_item_name_3': 'برنامج\nالإسبوع',
      'grid_item_name_4': 'إختبار',
      'grid_item_name_5': 'الإشتراكات',
      'grid_item_name_6': 'الدرجات',
      'grid_item_name_7': 'المسابقات',
      'grid_item_name_8': 'برنامج\nالإمتحان',
      'grid_item_name_9': 'المشاريع',
      'grid_item_name_10': 'الأفكار',
      'grid_item_name_11': 'المواد الدراسية',
      // For Calendar
      'schedule_title_page': 'برنامج الإسبوع',
      'Sun': 'الأحد',
      'Mon': 'الإثنين',
      'Tues': 'الثلاثاء',
      'Wed': 'الأربعاء',
      'Thurs': 'الخميس',
      // For filter page
      'filter_page_title': 'فلتر',
      'filter_desc': 'نحن بحاجة إلى بعض المعلومات للاستمرار',
      'title_field_1': 'اختر سنة',
      'title_field_2': 'حدد النوع',
      'type_0': 'الإمتحان النهائي',
      'type_1': 'الإمتحان النصفي',
      'type_2': 'إختبار',
      'button_text': 'التالي',
      'field_validation_text': 'لا يمكن أن يكون هذا الحقل فارغًا',
      // For grades
      'average': 'المعدل',
      // Profile
      'change_password': 'تغيير كلمة المرور',
      'about': 'عن',
      'help': 'يساعد',
      'contact': 'اتصال',
      'sign_out': 'تسجيل الخروج',
      'title_page': 'ملفك الشخصي',
      'profile_info_title': "معلومات الملف الشخصي",
      'class': 'الصف',
      'status': 'الحالة',
      'school': 'المدرسة',
      'rate': 'المعدل',
      'email-info': 'البريد الإلكتروني',
      'phone': 'الهاتف',
      'address': 'العنوان',
    },
  };
}
