import 'package:get/get.dart';

class ArabicEnglishLocal implements Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    "en": {
      'app_name': "Smart Path",
      // For introduction_pages
      'introduction_title': 'Welcome to Smart Path!',
      'introduction_content_0': 'You are in the right place',
      'introduction_content_1': 'Be with us on the amazing path',
      'introduction_content_2': 'anything very easy to use',
      // For login
      'sign_in': 'Sign In',
      'sign_in_desc': 'Hi there! Nice to see you again',
      'email': 'E-mail',
      'email-valid_empty': 'Email cannot be empty',
      'email-valid_weak': 'Email is invalid',
      'password': 'Password',
      'password_valid_empty': 'Password cannot be empty',
      'password_valid_weak': 'Password is too weak',
      'forgot_password': 'Forgot Password',
      // For reset password
      'reset_tite': 'Reset Password',
      'reset_desc': 'Please enter your password',
      'password_reset': 'Password',
      'password_confirm_reset': 'Confirm Password',
      'password_valid': 'Passwords are different',
      // NavBar
      'home': 'Home',
      'portfolio': 'Portfolio',
      'input': 'Input',
      'profile': 'Profile',
      //Home page student
      'app_bar_home_stu_title': 'Student Portfolio',
      'search_bar_home_hint': 'Looking for...',
      'welcome-content': 'Easily create and share\nyour own awesome portfolio',
      'grid_item_name_0': 'Class',
      'grid_item_name_1': 'Courses',
      'grid_item_name_2': 'Homeworks',
      'grid_item_name_3': 'Calendar',
      'grid_item_name_4': 'Quiz',
      'grid_item_name_5': 'Subscribe',
      'grid_item_name_6': 'Grades',
      'grid_item_name_7': 'Events',
      'grid_item_name_8': 'Exams',
      'grid_item_name_9': 'Project',
      'grid_item_name_10': 'Idea',
      'grid_item_name_11': 'Subjects',
      // Profile
      'edit_profile': 'Edit Profile',
      'change_password': 'Change Password',
      'about': 'About',
      'help': 'Help',
      'contact': 'Contact',
      'sign_out': 'Sign Out',
      'title_page': 'Your Profile',
      'profile-info-title': "Profile Info",
      'class': 'Class',
      'status': 'Status',
      'school': 'School',
      'rate': 'Rate',
      'email-info': 'E-mail',
      'phone': 'Phone',
      'address': 'Address',
    },
    "ar": {
      'app_name': "المسار الذكي",
      // For introduction_pages
      'introduction_title': 'مرحباً بكم في المسار الذكي!',
      'introduction_content_0': 'أنت في المكان المناسب',
      'introduction_content_1': 'كن معنا في الطريق المذهل',
      'introduction_content_2': 'هنا أي شيء سهل الاستخدام للغاية',
      // For login
      'sign_in': 'تسجيل الدخول',
      'sign_in_desc': 'مرحباً! سررت برؤيتك مجدداً',
      'email': 'البريد إلكتروني',
      'email-valid_empty': 'لا يمكن أن يكون البريد الإلكتروني فارغًا',
      'email-valid_weak': 'البريد الإلكتروني غير صالح',
      'password': 'كلمة السر',
      'password_valid_empty': 'لا يمكن أن تكون كلمة المرور فارغة',
      'password_valid_weak': 'كلمة المرور ضعيفة جدًا',
      'forgot_password': 'هل نسيت كلمة السر',
      // For reset password
      'reset_tite': 'إعادة تعيين كلمة المرور',
      'reset_desc': 'الرجاء إدخال كلمة المرور الخاصة بك',
      'password_reset': 'كلمة المرور',
      'password_confirm_reset': 'تأكيد كلمة المرور',
      'password_valid': 'كلمات المرور مختلفة',
      // NavBar
      'home': 'الرئيسية',
      'portfolio': 'الإنجازات',
      'input': 'إدخال',
      'profile': 'الملف الشخصي',
      //Home page student
      'app_bar_home_stu_title': 'ملف الطالب',
      'search_bar_home_hint': 'ابحث عن',
      'welcome-content': 'قم بإنشاء ومشاركة\nمحفظتك الرائعة بسهولة',
      'grid_item_name_0': 'الفصل الدراسي',
      'grid_item_name_1': 'الدورات',
      'grid_item_name_2': 'الوظائف',
      'grid_item_name_3': 'التقويم',
      'grid_item_name_4': 'اختبار',
      'grid_item_name_5': 'الإشتراكات',
      'grid_item_name_6': 'الدرجات',
      'grid_item_name_7': 'المسابقات',
      'grid_item_name_8': 'الإمتحانات',
      'grid_item_name_9': 'المشاريع',
      'grid_item_name_10': 'الأفكار',
      'grid_item_name_11': 'المواد الدراسية',
      // Profile
      'edit_profile': 'تعديل الملف الشخصي',
      'change_password': 'تغيير كلمة المرور',
      'about': 'عن',
      'help': 'يساعد',
      'contact': 'اتصال',
      'sign_out': 'تسجيل الخروج',
      'title_page': 'ملفك الشخصي',
      'profile-info-title': "معلومات الملف الشخصي",
      'class': 'الصف',
      'status': 'الحالة',
      'school': 'المدرسة',
      'rate': 'المعدل',
      'email-info': 'البريد الإلكتروني',
      'phone': 'الهاتف',
      'address': 'العنوان',
    },
  };
}



//       'footer_card_title_home': 'Student Portfolio',
//       'footer_card_desc_home':
//           'Easily create and share \n your own awesome portfolio',

//       'footer_card_title_home': 'ملف الطالب',
//       'footer_card_desc_home': 'أنشئ وشارك ملفك الرائع \n بكل سهولة',